homeSpace/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('authusers.urls')),
    path('user/',include('django.contrib.auth.urls')),

    path('post/', include('announcement.urls')),
    path('', include('main.urls')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

handler404 = "homeSpace.views.page_not_found_view"

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from .views import (
    HomePageView,SubscribeView,AboutPageView,ContactPageView,
    AnnouncmentPageView,ContactWithAgentView
)

app_name='main'

urlpatterns = [
    path('', HomePageView.as_view(),name='index'),
    path('subscribe/', SubscribeView.as_view(),name='subscribe'),
    path('about/', AboutPageView.as_view(),name='about'),
    path('contact/', ContactPageView.as_view(),name='contact'),
    path('announcement/', AnnouncmentPageView.as_view(), name='announcement'),

    path('contact-with-agent/<slug:slug>/', ContactWithAgentView.as_view(), name='contact'), # ariza qoldirish uchun
]

announcement/models.py
from django.db import models
from django.urls import reverse

from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.text import slugify

from django.contrib.auth import get_user_model

User = get_user_model()

from authusers.models import Agents


class Regions(models.Model):
    region = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.region

    class Meta:
        verbose_name_plural = 'Regions'
        verbose_name = 'Region'


class Districts(models.Model):
    region = models.ForeignKey(Regions, on_delete=models.CASCADE)
    district = models.CharField(max_length=150)

    def __str__(self):
        return self.district

    class Meta:
        verbose_name_plural = 'Districts'
        verbose_name = 'District'


class Posts(models.Model):
    resturant = 'resturant';
    market = 'market';
    float = 'float';
    yard = 'yard'
    type = [(resturant, 'resturant'), (market, 'market'), (float, 'float'), (yard, 'yard')]

    sale = 'buy';
    rent = 'rent'
    type_status = [(sale, 'Buy'), (rent, 'Rent')]

    title = models.CharField(max_length=255, unique=True)
    home_type = models.CharField(max_length=20, choices=type, default=type[2][0])
    type = models.CharField(max_length=20, choices=type_status, default=type_status[0][0])
    price = models.FloatField('price ($)', default=0, blank=True, validators=[MinValueValidator(0)])
    year_build = models.PositiveIntegerField(default=0, blank=True, validators=[MinValueValidator(0)])
    more_info = models.TextField('more info', default="more info ...")
    area = models.FloatField('area (m.kv)', default=1)
    picture = models.ImageField(
        upload_to=f"announcement/%Y/%m/%d/announcement")
    picture2 = models.ImageField(
        upload_to=f"announcement/%Y/%m/%d/announcement")
    picture3 = models.ImageField(
        upload_to=f"announcement/%Y/%m/%d/announcement")
    beds = models.PositiveIntegerField(
        'badroom', validators=[MinValueValidator(1), MaxValueValidator(5)], default=1)
    baths = models.PositiveIntegerField(
        'batheroom', validators=[MinValueValidator(1), MaxValueValidator(5)], default=1)
    garages = models.PositiveIntegerField(
        'garages', validators=[MinValueValidator(0), MaxValueValidator(5)], default=1)
    tel_num = models.CharField("telefon number:", max_length=40, default="+998")
    region = models.ForeignKey(Regions, on_delete=models.CASCADE)
    district = models.ForeignKey(Districts, on_delete=models.CASCADE)
    adress = models.CharField(max_length=255, null=True)
    diller = models.ForeignKey(Agents, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255, db_index=True, blank=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    is_publish = models.BooleanField(default=False)
    is_send_mail = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.picture.delete()
        self.picture2.delete()
        self.picture3.delete()
        super().delete(*args, **kwargs)

    def get_absolute_url(self):
        kwargs = {'slug': self.slug}
        return reverse('post-detail', kwargs=kwargs)

    def get_absolute_url_edit(self):
        kwargs = {'slug': self.slug}
        return reverse('post-edit', kwargs=kwargs)

    def get_absolute_url_delete(self):
        kwargs = {'slug': self.slug}
        return reverse('post-delete', kwargs=kwargs)

    def get_absolute_url_comment(self):
        kwargs = {'slug': self.slug}
        return reverse('comment', kwargs=kwargs)

    def get_contact_with_agent_url(self):
        kwargs = {'slug': self.slug}
        return reverse('main:contact', kwargs=kwargs)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        ordering = ['-created_at']
        verbose_name_plural = 'Posts'
        verbose_name = 'Post'


class PostComment(models.Model):
    comment = models.TextField("your comment:")
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post.title} | {self.author} | comment"

templates/about.html
{% extends 'base.html' %}
{% load static %}
{%  block title %}HomeSpace - About page{% endblock %}
{% block content %}
<div class="site-blocks-cover inner-page-cover overlay" style="background-image: url('{% static "images/hero_bg_2.jpg" %}');" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-10">
        <h1 class="mb-2">About Us</h1>
        <div><a href="\">Home</a> <span class="mx-2 text-white">&bullet;</span> <strong class="text-white">About</strong></div>
      </div>
    </div>
  </div>
</div>

<div class="site-section border-bottom">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6" data-aos="fade-up" data-aos-delay="100">
        <img src="{% static 'images/about.jpg' %}" alt="Image" class="img-fluid">
      </div>
      <div class="col-md-5 ml-auto"  data-aos="fade-up" data-aos-delay="200">
        <div class="site-section-title mb-3">
          <h2>Our Company</h2>
        </div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus in cum odio.</p>
        <p>Illum repudiandae ratione facere explicabo. Consequatur dolor optio iusto, quos autem voluptate ea? Sunt laudantium fugiat, mollitia voluptate? Modi blanditiis veniam nesciunt architecto odit voluptatum tempore impedit magnam itaque natus!</p>
      </div>
    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-6 order-md-2" data-aos="fade-up" data-aos-delay="100">
        <img src="{% static 'images/office.jpg' %}" alt="Image" class="img-fluid">
      </div>
      <div class="col-md-5 mr-auto order-md-1"  data-aos="fade-up" data-aos-delay="200">
        <div class="site-section-title mb-3">
          <h2>Our Office</h2>
        </div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus in cum odio.</p>
        <p>Illum repudiandae ratione facere explicabo. Consequatur dolor optio iusto, quos autem voluptate ea? Sunt laudantium fugiat, mollitia voluptate? Modi blanditiis veniam nesciunt architecto odit voluptatum tempore impedit magnam itaque natus!</p>
      </div>
    </div>
  </div>
</div>


{% if founders %}
<div class="bg-light border-top">
  <div class="site-section">
    <div class="container">
        <div class="row mb-5 justify-content-center">
          <div class="col-md-7">
            <div class="site-section-title text-center">
              <h2>Founders</h2>
            </div>
          </div>
        </div>
        <div class="row block-13">

          <div class="nonloop-block-13 owl-carousel">
            {% for obj in founders %}
              <div class="slide-item">
                <div class="team-member text-center">
                  <img {% if  obj.profile_img %}src="{{obj.profile_img.url}}"{% else %}src="{% static 'images/person_1.jpg' %}"{% endif %} alt="Image" class="img-fluid mb-4 w-50 rounded-circle mx-auto">
                  <div class="text p-1">
                    <h2 class="mb-2 font-weight-light text-black h4">{{obj.agent.username}}</h2>
                    <span class="d-block mb-3 text-white-opacity-05">Founder</span>
                    <p class="mb-5">{{obj.agent_info|safe}}</p>
                    <p>
                      <a href="{{obj.facebook}}" class="text-black p-2"><span class="icon-facebook"></span></a>
                      <a href="{{obj.twitter}}" class="text-black p-2"><span class="icon-twitter"></span></a>
                      <a href="{{obj.linkedn}}" class="text-black p-2"><span class="icon-linkedin"></span></a>
                    </p>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>

        </div>
    </div>
  </div>
</div>
{% endif %}

{% if agents %}  
<div class="bg-light border-top">
  {% include "our_agents.html" %}
</div>
{% endif %}
{% endblock %}

templates/base.html
{% load static %}
{% load active_link_tags %}
{% url 'main:index' as index %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{%  block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,700,900|Roboto+Mono:300,400,500">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/mediaelementplayer.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/fl-bigmug-line.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {%  block css %}{% endblock %}
  </head>
  <body>

  <div class="site-loader" style='background: "{% static 'url(/images/loader.gif)' %}" center no-repeat #fff;'></div>

  <div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->

    <div class="border-bottom bg-white top-bar">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-6 col-md-6">
            <p class="mb-0">
              <a href="tel:+998993968839" class="mr-3"><span class="text-black fl-bigmug-line-phone351"></span> <span class="d-none d-md-inline-block ml-2">+998993968839</span></a>
              <a href="mailto:asliddintukhtasinov5@gmail.com"><span class="text-black fl-bigmug-line-email64"></span> <span class="d-none d-md-inline-block ml-2">asliddintukhtasinov5@gmail.com</span></a>
            </p>
          </div>
          <div class="col-6 col-md-6 text-right">
            <a href="https://t.me/Asliddindev" class="mr-3"><span class="text-black icon-facebook"></span></a>
            <a href="https://t.me/Asliddindev" class="mr-3"><span class="text-black icon-twitter"></span></a>
            <a href="https://t.me/Asliddindev" class="mr-0"><span class="text-black icon-linkedin"></span></a>
          </div>
        </div>
      </div>

    </div>

    <div class="site-navbar">
        <div class="container py-1">
          <div class="row align-items-center">

            <div class="col-8 col-md-8 col-lg-4">
              <h1 class=""><a href="\" class="h5 text-uppercase text-black"><strong>HomeSpace<span class="text-danger">.</span></strong></a></h1>
            </div>
            <div class="col-4 col-md-4 col-lg-8">
              <nav class="site-navigation text-right text-md-right" role="navigation">

                <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3"><a href="#" class="site-menu-toggle js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>

                <ul class="site-menu js-clone-nav d-none d-lg-block">
                  <li class="{% if index == request.path %}active{% endif %}">
                    <a href="{% url 'main:index' %}">Home</a>
                  </li>
                  <li class="has-children {% active_link 'main:announcement' %}">
                    <a href="{% url 'main:announcement' %}">Announcement</a>
                    <ul class="dropdown">
                      <li><a href="{% url 'main:announcement' %}?type=buy">Buy</a></li>
                      <li><a href="{% url 'main:announcement' %}?type=rent">Rent</a></li>
                    </ul>
                  </li>
                  <li class="{% active_link 'main:about' %}"><a href="{% url 'main:about' %}">About</a></li>
                  <li class="{% active_link 'main:contact' %}"><a href="{% url 'main:contact' %}">Contact</a></li>

                  {% if user.is_authenticated %}
                    <li class="has-children {% active_link 'user_page' %}">
                      <a href="{% url 'user_page' %}">{{ user.username|title }}</a>
                      <ul class="dropdown">
                        <li><a href="{% url 'logout' %}">Log out</a></li>
                        <li><a href="{% url 'edit_profile' %}">Edite profile</a></li>
                        {% if user.is_agent %}
                          <li><a href="{% url 'contact-with-client-page' %}">contact with clients</a></li>
                          <li><a href="{% url 'announcment_to_be_published' %}">announcment to be published</a></li>
                        {% else %}
                          <li><a href="{% url 'create_post' %}">Add anouncment</a></li>
                        {% endif %}
                      </ul>
                    </li>
                  {% else %}
                    <li class="{% active_link 'login' %}"><a href="{% url 'login' %}">Log in</a></li>
                    <li class="{% active_link 'signup' %}"><a href="{% url 'signup' %}">Sign Up</a></li>
                  {% endif %}

                </ul>

              </nav>
            </div>

          </div>
        </div>
    </div>

  </div>
<!--navbar end-->

  {% block content %}
  {% endblock %}

<!--foter started-->
    <footer class="site-footer">
      <div class="container">
        <div class="row">

          <div class="col-lg-4">
            <div class="mb-5">
              <h3 class="footer-heading mb-4">About HomeSpace</h3>
              <p>Bu online uylar bozori nafaqat uylar balki boshqa ko'chmas(restaran, magazin,..) mulklarni ham. Biz sizga ijaraga mulk taklif etishimiz va mulkingizni sotish ga yordam beramiz.</p>
            </div>
          </div>

          <div class="col-lg-4 mb-5 mb-lg-0">
            <div class="row mb-5">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Navigations</h3>
              </div>
              <div class="col-md-6 col-lg-6">
                <ul class="list-unstyled">
                  <li><a href="\">Home</a></li>
                  <li><a href="{% url 'main:announcement' %}?type=buy">Buy</a></li>
                  <li><a href="{% url 'main:announcement' %}?type=rent">Rent</a></li>
                  <li><a href="{% url 'main:announcement' %}">Announcement</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-6">
                <ul class="list-unstyled">
                  <li><a href="{% url 'main:about' %}">About Us</a></li>
                  <li><a href="{% url 'main:contact' %}">Contact Us</a></li>
                    {% if user.is_authenticated %}
                      <li><a href="{% url 'logout' %}">Log out</a></li>
                    {% else %}
                      <li><a href="{% url 'signup' %}">Sign Up</a></li>
                      <li><a href="{% url 'login' %}">Log in</a></li>
                    {%endif%}
                </ul>
              </div>
            </div>
          </div>

          <div class="col-lg-4 mb-5 mb-lg-0">
            <h3 class="footer-heading mb-4">Follow Us</h3>

                <div>
                  <a href="https://t.me/Asliddindev" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
                  <a href="https://t.me/Asliddindev" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
                  <a href="https://t.me/Asliddindev" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                  <a href="https://t.me/Asliddindev" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
                </div>

          </div>

        </div>

        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;</script><script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
              <br>
            Copyright &copy;</script><script>document.write(new Date().getFullYear());</script> This template's backend part and some frontend part are made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://t.me/Asliddindev" target="_blank" >Asliddin Tuxtasinov</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>
        </div>

      </div>
    </footer>
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/mediaelement-and-player.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  {%  block js %}{% endblock %}
  </body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{%  block title %}HomeSpace - Contact page{% endblock %}
{% block content %}
<div class="site-blocks-cover inner-page-cover overlay" style="background-image: url('{% static "images/hero_bg_2.jpg" %}');" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-10">
        <h1 class="mb-2">Contact Us</h1>
        <div><a href="\">Home</a> <span class="mx-2 text-white">&bullet;</span> <strong class="text-white">Contact</strong></div>
      </div>
    </div>
  </div>
</div>

<div class="site-section">
    {% for msg in messages %}
      <div class="container alert alert-success alert-dismissible fade show" role="alert">
        {{msg}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
  {% endfor %}
  <div class="container">
        <div class="row">
       
          <div class="col-md-12 col-lg-8 mb-5">

            <form method="POST" class="p-5 bg-white border card">{% csrf_token %}
              {% for form in contact_form %}
                <div class="row form-group">
                  <div class="col-md-12">
                    <div class="font-weight-bold">
                      {{form.label}}
                    </div>
                    {{form}}
                    {{form.errors}}
                  </div>
                </div>
              {% endfor %}
              <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Send Message" class="btn btn-primary  py-2 px-4 rounded-0">
                </div>
              </div>

            </form>
          </div>
          <div class="col-lg-4">
            <div class="p-4 mb-3 bg-white card">
              <h3 class="h6 text-black mb-3 text-uppercase">Contact Info</h3>
              <p class="mb-0 font-weight-bold">Manzil</p>
              <p class="mb-4">20-uy Avazboy ko'chasi. Rishton tum, Farg'ona vil, O'zbekiston</p>

              <p class="mb-0 font-weight-bold">Telefon</p>
              <p class="mb-4"><a href="tel:+998993968839">+99899-396-88-39</a></p>

              <p class="mb-0 font-weight-bold">Email manzil</p>
              <p class="mb-0"><a href="mailto:asliddintukhtasinov5@gmail.com">asliddintukhtasinov5@gmail.com</a></p>

            </div>
          </div>

        </div>
      </div>
</div>

{% include 'our_agents.html' %}

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{%  block title %}HomeSpace - Welcome{% endblock %}
{% block content %}
{% for msg in messages %}
  <div class="container alert alert-success alert-dismissible fade show" role="alert">
    {{msg}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  </div>
{% endfor %}

    {% include 'main-posts.html' %}
    {% include 'main-search.html' %}

<div class="site-section site-section-sm bg-light">
    <div class="container">

      <div class="row mb-5">
        <div class="col-12">
          <div class="site-section-title">
            <h2>New Properties for You</h2>
          </div>
        </div>
      </div>

      {% include 'posts.html' %}
      {% include 'pagination.html' %}

    </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-7 text-center mb-5">
        <div class="site-section-title">
          <h2>Our Services</h2>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 col-lg-4 mb-4">
        <a href="#" class="service text-center border rounded">
          <span class="icon flaticon-house"></span>
          <h2 class="service-heading">Research Subburbs</h2>
          <p><span class="read-more">Learn More</span></p>
        </a>
      </div>
      <div class="col-md-6 col-lg-4 mb-4">
        <a href="#" class="service text-center border rounded">
          <span class="icon flaticon-sold"></span>
          <h2 class="service-heading">Sold Houses</h2>
          <p><span class="read-more">Learn More</span></p>
        </a>
      </div>
      <div class="col-md-6 col-lg-4 mb-4">
        <a href="#" class="service text-center border rounded">
          <span class="icon flaticon-camera"></span>
          <h2 class="service-heading">Security Priority</h2>
          <p><span class="read-more">Learn More</span></p>
        </a>
      </div>

      <div class="col-md-6 col-lg-4 mb-4">
        <a href="#" class="service text-center border rounded">
          <span class="icon flaticon-house"></span>
          <h2 class="service-heading">Research Subburbs</h2>
          <p><span class="read-more">Learn More</span></p>
        </a>
      </div>
      <div class="col-md-6 col-lg-4 mb-4">
        <a href="#" class="service text-center border rounded">
          <span class="icon flaticon-sold"></span>
          <h2 class="service-heading">Sold Houses</h2>
          <p><span class="read-more">Learn More</span></p>
        </a>
      </div>
      <div class="col-md-6 col-lg-4 mb-4">
        <a href="#" class="service text-center border rounded">
          <span class="icon flaticon-camera"></span>
          <h2 class="service-heading">Security Priority</h2>
          <p><span class="read-more">Learn More</span></p>
        </a>
      </div>
    </div>
  </div>
</div>

{% if agents %} 
{% include "our_agents.html" %}
{% endif %}
<div class="site-section site-section-sm bg-primary">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-8">
        <h2 class="text-white">Eng so'ngi e'lonlardan habardor bo'lish uchun bizga obuna bo'ling!</h2>
        <p class="lead text-white-5">Email pochtangizni kiriting, biz sizga eng songi e'lonlar haqida xabar beramiz!</p>
      </div>
      <div class="col-md-4 text-center">
        <form action="{% url 'main:subscribe' %}" method="post">
          {% csrf_token %}
          {{subsribe_form|crispy}}
          <input type="submit" class="btn btn-outline-primary btn-block py-3 btn-lg" value="obuna bo'lish">
        </form>
      </div>
    </div>
  </div>
</div>
    
{% endblock %}

{%  block js %}
<script>
    // ajax for filter => regions and districts
    $("#id_region").change(function () {
        const url = $("#postForm").attr("data-cities-url");
        const regionId = $(this).val();
        console.log(regionId)

        $.ajax({
            url: url,
            data: {
                'region_id': regionId
            },
            success: function (data) {
                $("#id_district").html(data);
            }
        });
    });
</script>
{% endblock %}

templates/main-posts.html
{% load static %}
<div class="slide-one-item home-slider owl-carousel">
    {% for post in main_posts %}
      <div class="site-blocks-cover" style="background-image: url({% static 'images/hero_bg_1.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">

        <div class="text">
          <h2>{{post.title|title}}</h2>
          <p class="location"><span class="property-icon icon-room"></span>{{ post.region }}, {{ post.district }}</p>
          <p class="mb-2"><strong>${{post.price}}</strong></p>


          <p class="mb-0"><a href="{{post.get_absolute_url}}" class="text-uppercase small letter-spacing-1 font-weight-bold">More Details</a></p>

        </div>
      </div>
    {% endfor %}
</div>

templates/properties.html
{% extends 'base.html' %}
{% load static %}
{%  block title %}HomeSpace - Properties page{% endblock %}
{% block content %}

{% include 'main-posts.html' %}
{% include 'main-search.html' %}

<div class="site-section site-section-sm bg-light">
      <div class="container">

        <div class="row mb-5">
          <div class="col-12">
            <div class="site-section-title">
              <h2>New Properties for You</h2>
            </div>
          </div>
        </div>
        {% include 'posts.html' %}

        {% include 'pagination.html' %}

      </div>
    </div>

{% endblock %}
{%  block js %}
<script>
    // ajax for filter => regions and districts
    $("#id_region").change(function () {
        const url = $("#postForm").attr("data-cities-url");
        const regionId = $(this).val();
        console.log(regionId)

        $.ajax({
            url: url,
            data: {
                'region_id': regionId
            },
            success: function (data) {
                $("#id_district").html(data);
            }
        });
    });
</script>
{% endblock %}